/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  EasyCalendar as EasyCalendar
} from './components/easy-calendar/easy-calendar';

declare global {
  interface HTMLEasyCalendarElement extends EasyCalendar, HTMLElement {
  }
  var HTMLEasyCalendarElement: {
    prototype: HTMLEasyCalendarElement;
    new (): HTMLEasyCalendarElement;
  };
  interface HTMLElementTagNameMap {
    "easy-calendar": HTMLEasyCalendarElement;
  }
  interface ElementTagNameMap {
    "easy-calendar": HTMLEasyCalendarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "easy-calendar": JSXElements.EasyCalendarAttributes;
    }
  }
  namespace JSXElements {
    export interface EasyCalendarAttributes extends HTMLAttributes {
      
    }
  }
}

